#!/bin/bash
INDENT=`which indent`
if [ -z $INDENT ]
then
	echo GNU indent not found in \$PATH. Install it and come back.
	exit 1
fi
$INDENT -nbad -bap -bbo -nbc -br -brs -ncdb -ce -ci4 -cli0 -ncs -d0 -di1 -nfc1 \
-nfca -hnl -i8 -ip0 -l80 -lp -npcs -nprs -npsl -saf -sai -saw -sbi0 -nsc -nsob \
-nss -ts8 -T firmware_image_t -T memmap_t -T p80211hdr_t -T wlandevice_t \
-T TIWLAN_DC -T UINT -T UINT8 -T UINT16 -T UINT32 $*
