name: check_approver

on:
  pull_request:
    branches: [ main, master, test ]

jobs:
  check_approver:
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: read
    
    steps:
    - name: check approver
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NO: ${{ github.event.number }}
        REPO: ${{ github.event.repository.full_name }}
      run: |
        ls -altr
        gh pr view $PR_NO -R $REPO--json author --jq ".author.login" >> editors.txt
        gh pr view $PR_NO -R $REPO --json commits --jq '.commits[].authors[].login' >> editors.txt
        uniq editors.txt uniq-editors.txt
        gh pr view $PR_NO -R $REPO --json reviews --jq '.reviews[] | select(.state == "APPROVED") | .author.login' >> approvers.txt
        # count number of occurrences of each approver in editors file and check
        # if we found any approver who is not in editors file
        cat approvers.txt | xargs -I X grep -Fxc X uniq-editors.txt | grep "0"
