name: check_approver

on:
  pull_request:
    types: [ open ]
    branches: [ main, master, test ]

jobs:
  check_approver:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    
    permissions:
      pull-requests: read
    
    steps:
    - name: check approver
      env:
        PR_NO: ${{ github.event.pull_request.number }}
      run: |
        gh pr view $PR_NO --json author --jq ".author.login" >> editors.txt
        gh pr view $PR_NO --json commits --jq '.commits[].authors[].login' >> editors.txt
        uniq editors.txt uniq-editors.txt
        gh pr view $PR_NO --json reviews --jq '.reviews[] | select(.state == "APPROVED") | .author.login' >> approvers.txt
        # count number of occurrences of each approver in editors file and check
        # if we found any approver who is not in editors file
        cat approvers.txt | xargs -I X grep -Fxc X uniq-editors.txt | grep "0"
